routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', 'ShareController@welcome')->name('welcome');


Route::get('/home', 'HomeController@index')->name('home');

Route::post('/upload', 'UploadController@upload');



Route::resource('shares', 'ShareController');

Route::get('/image', function () {
    return view('image');
});

app/Share.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Share extends Model
{
    protected $fillable = [
    'share_name',
    'share_price',
    'share_qty'
  ];
}

app/Http/Controllers/ShareController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Share;


class ShareController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $shares = Share::all();

        return view('shares.index', compact('shares'));
    }

    public function welcome()
    {
       $shares = Share::first();
       
       $images = \File::allFiles(public_path('racing'));
       $images1 = \File::allFiles(public_path('awards'));
       $images2 = \File::allFiles(public_path('family'));



        return view('welcome', compact('shares', 'images','images1','images2'));
    }





    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('shares.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'share_name'=>'required',
        'share_price'=> 'required|integer',
        'share_qty' => 'required|integer'
      ]);
      $share = new Share([
        'share_name' => $request->get('share_name'),
        'share_price'=> $request->get('share_price'),
        'share_qty'=> $request->get('share_qty')
      ]);
      $share->save();
      return redirect('/shares')->with('success', 'Website (www.emmanuelbako.com) updated now!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $share = Share::find($id);

        return view('shares.edit', compact('share'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
        'share_name'=>'required',
        'share_price'=> 'required|integer',
        'share_qty' => 'required|integer'
      ]);

      $share = Share::find($id);
      $share->share_name = $request->get('share_name');
      $share->share_price = $request->get('share_price');
      $share->share_qty = $request->get('share_qty');
      $share->bannertitle = $request->get('bannertitle');
      $share->bannercontent = $request->get('bannercontent');
      $share->aboutme = $request->get('aboutme');
      $share->background = $request->get('background');
      $share->education = $request->get('education');
      $share->name = $request->get('name');
      $share->age = $request->get('age');
      $share->achievementshead = $request->get('achievementshead');
      $share->achv1title = $request->get('achv1title');
      $share->achv1body = $request->get('achv1body');
      $share->achv2title = $request->get('achv2title');
      $share->achv2body = $request->get('achv2body');
      $share->achv3body = $request->get('achv3body');
      $share->achv3title = $request->get('achv3title');
      $share->achv4title = $request->get('achv4title');
      $share->achv4body = $request->get('achv4body');
      $share->achv5title = $request->get('achv5title');
      $share->achv5body = $request->get('achv5body');
      $share->achv6title = $request->get('achv6title');
      $share->achv6body = $request->get('achv6body');
      $share->achv7title = $request->get('achv7title');
      $share->achv7body = $request->get('achv7body');
      $share->achv8title = $request->get('achv8title');
      $share->achv8body = $request->get('achv8body');
      $share->achv9title = $request->get('achv9title');
      $share->achv9body = $request->get('achv9body');
      $share->achv10title = $request->get('achv10title');
      $share->achv10body = $request->get('achv10body');
      $share->achv11title = $request->get('achv11title');
      $share->achv11body = $request->get('achv11body');
      $share->achv12title = $request->get('achv12title');
      $share->achv12body = $request->get('achv12body');
      $share->achv13title = $request->get('achv13title');
      $share->achv13body = $request->get('achv13body');
      $share->phone = $request->get('phone');
      $share->email = $request->get('email');
      $share->address = $request->get('address');
      $share->video1 = $request->get('video1');
      $share->video2 = $request->get('video2');
      $share->video3 = $request->get('video3');
      $share->video4 = $request->get('video4');
      $share->video5 = $request->get('video5');
      $share->video6 = $request->get('video6');
      $share->teamdescription = $request->get('teamdescription');
      $share->team1 = $request->get('team1');
      $share->team2 = $request->get('team2');
      $share->team3 = $request->get('team3');
      $share->team4 = $request->get('team4'); 
      $share->team1t = $request->get('team1t');
      $share->team2t = $request->get('team2t');
      $share->team3t = $request->get('team3t');
      $share->team4t = $request->get('team4t'); 
      $share->testimony = $request->get('testimony');
      $share->testimonyoc = $request->get('testimonyoc'); 
      $share->testimonyname = $request->get('testimonyname');
      $share->fb = $request->get('fb');
      $share->twitter = $request->get('twitter');
      $share->instagram = $request->get('instagram');     
      $share->save();

      return redirect('/shares')->with('success', 'www.emmanuelbako.com has been updated');
}
    

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $share = Share::find($id);
     $share->delete();

     return redirect('/shares')->with('success', 'Stock has been deleted Successfully');
    }
}

resources/views/shares/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('shares.store') }}">
          <div class="form-group">
              @csrf
              <label for="name">Share Name:</label>
              <input type="text" class="form-control" name="share_name"/>
          </div>
          <div class="form-group">
              <label for="price">Share Price :</label>
              <input type="text" class="form-control" name="share_price"/>
          </div>
          <div class="form-group">
              <label for="quantity">Share Quantity:</label>
              <input type="text" class="form-control" name="share_qty"/>
          </div>
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/shares/edit.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    EDIT THE WHOLE WEBSITE BODY TEXT INCLUDING LINKS!
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('shares.update', $share->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="name">:</label>
          <input type="text" class="form-control" name="share_name" value="{{ $share->share_name }}" />
        </div>
        <div class="form-group">
          <label for="price">1 IGNORE THIS FIELD:</label>
          <input type="text" class="form-control" name="share_price" value="{{ $share->share_price }}" />
        </div>
        <div class="form-group">
          <label for="quantity">1 IGNORE THIS FIELD:</label>
          <input type="text" class="form-control" name="share_qty" value="{{ $share->share_qty }}" />
        </div>

        <div class="form-group">
          <label for="bannertitle">Banner Title:</label>
          <input type="text" class="form-control" name="bannertitle" value="{{ $share->bannertitle }}" />
        </div>

          <div class="form-group">
          <label for="bannercontent">Banner Content:</label>
          <input type="text" class="form-control" name="bannercontent" value="{{ $share->bannercontent }}" />
        </div>

          <div class="form-group">
          <label for="aboutme">About Me:</label>
          <input type="text" class="form-control" name="aboutme" value="{{ $share->aboutme }}" />
        </div>

        <div class="form-group">
          <label for="background">Background:</label>
          <input type="text" class="form-control" name="background" value="{{ $share->background }}" />
        </div>

        <div class="form-group">
          <label for="education">Education:</label>
          <input type="text" class="form-control" name="education" value="{{ $share->education }}" />
        </div>


        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" name="name" value="{{ $share->name }}" />
        </div>

        <div class="form-group">
          <label for="age">Age:</label>
          <input type="text" class="form-control" name="age" value="{{ $share->age }}" />
        </div>

        <div class="form-group">
          <label for="achievementshead">Achievements Head:</label>
          <input type="text" class="form-control" name="achievementshead" value="{{ $share->achievementshead }}" />
        </div>

        <div class="form-group">
          <label for="achv1title">Achievement 1 title :</label>
          <input type="text" class="form-control" name="achv1title" value="{{ $share->achv1title }}" />
        </div>

          <div class="form-group">
          <label for="achv1body">Achievement 1 body :</label>
          <input type="text" class="form-control" name="achv1body" value="{{ $share->achv1body }}" />
          </div>

          <div class="form-group">
          <label for="achv2title">Achievement 2 title :</label>
          <input type="text" class="form-control" name="achv2title" value="{{ $share->achv2title }}" />
          </div>

          <div class="form-group">
          <label for="achv2body">Achievement 2 body :</label>
          <input type="text" class="form-control" name="achv2body" value="{{ $share->achv2body }}" />
          </div>

          <div class="form-group">
          <label for="achv3title">Achievement 3 title :</label>
          <input type="text" class="form-control" name="achv3title" value="{{ $share->achv3title }}" />
          </div>

          <div class="form-group">
          <label for="achv3body">Achievement 3 body :</label>
          <input type="text" class="form-control" name="achv3body" value="{{ $share->achv3body }}" />
          </div>

          <div class="form-group">
          <label for="achv4title">Achievement 4 title :</label>
          <input type="text" class="form-control" name="achv4title" value="{{ $share->achv4title }}" />
          </div>

          <div class="form-group">
          <label for="achv4body">Achievement 4 body :</label>
          <input type="text" class="form-control" name="achv4body" value="{{ $share->achv4body }}" />
          </div>

          <div class="form-group">
          <label for="achv5title">Achievement 5 title :</label>
          <input type="text" class="form-control" name="achv4title" value="{{ $share->achv5title }}" />
          </div>

          <div class="form-group">
          <label for="achv5body">Achievement 5 body :</label>
          <input type="text" class="form-control" name="achv5body" value="{{ $share->achv5body }}" />
          </div>

          <div class="form-group">
          <label for="achv6title">Achievement 6 title :</label>
          <input type="text" class="form-control" name="achv6title" value="{{ $share->achv6title }}" />
          </div>

          <div class="form-group">
          <label for="achv6title">Achievement 6 title :</label>
          <input type="text" class="form-control" name="achv6title" value="{{ $share->achv6title }}" />
          </div>

          <div class="form-group">
          <label for="achv7title">Achievement 7 title :</label>
          <input type="text" class="form-control" name="achv4title" value="{{ $share->achv7title }}" />
          </div>

          <div class="form-group">
          <label for="achv7body">Achievement 7 body :</label>
          <input type="text" class="form-control" name="achv4body" value="{{ $share->achv7body }}" />
          </div>

          <div class="form-group">
          <label for="achv8body">Achievement 8 body :</label>
          <input type="text" class="form-control" name="achv7body" value="{{ $share->achv8body }}" />
          </div>

          <div class="form-group">
          <label for="achv8body">Achievement 8 body :</label>
          <input type="text" class="form-control" name="achv4body" value="{{ $share->achv8body }}" />
          </div>

          <div class="form-group">
          <label for="achv9title">Achievement 9 title :</label>
          <input type="text" class="form-control" name="achv9title" value="{{ $share->achv9title }}" />
          </div>

          <div class="form-group">
          <label for="achv9body">Achievement 9 body :</label>
          <input type="text" class="form-control" name="achv9body" value="{{ $share->achv9body }}" />
          </div>

          <div class="form-group">
          <label for="achv10title">Achievement 10 title :</label>
          <input type="text" class="form-control" name="achv4title" value="{{ $share->achv4title }}" />
          </div>

          <div class="form-group">
          <label for="achv10body">Achievement 10 body :</label>
          <input type="text" class="form-control" name="achv10body" value="{{ $share->achv10body }}" />
          </div>

          <div class="form-group">
          <label for="achv11title">Achievement 11 title :</label>
          <input type="text" class="form-control" name="achv11title" value="{{ $share->achv11title }}" />
          </div>

          <div class="form-group">
          <label for="achv11body">Achievement 11 body :</label>
          <input type="text" class="form-control" name="achv11body" value="{{ $share->achv11body }}" />
          </div>

          <div class="form-group">
          <label for="achv12title">Achievement 12 title :</label>
          <input type="text" class="form-control" name="achv12title" value="{{ $share->achv12title }}" />
          </div>

          <div class="form-group">
          <label for="achv12body">Achievement 12 body :</label>
          <input type="text" class="form-control" name="achv12body" value="{{ $share->achv12body }}" />
          </div>

          <div class="form-group">
          <label for="phone">Phone number :</label>
          <input type="text" class="form-control" name="phone" value="{{ $share->phone }}" />
          </div>

          <div class="form-group">
          <label for="email">Email :</label>
          <input type="text" class="form-control" name="email" value="{{ $share->email }}" />
          </div>

          <div class="form-group">
          <label for="address">Address :</label>
          <input type="text" class="form-control" name="address" value="{{ $share->address }}" />
          </div>

          <div class="form-group">
          <label for="video1">Video 1 Link :</label>
          <input type="text" class="form-control" name="video1" value="{{ $share->video1 }}" />
          </div>

          <div class="form-group">
          <label for="video2">Video 2 Link :</label>
          <input type="text" class="form-control" name="video2" value="{{ $share->video2 }}" />
          </div>

          <div class="form-group">
          <label for="video3">Video 3 Link :</label>
          <input type="text" class="form-control" name="video3" value="{{ $share->video3 }}" />
          </div>

           <div class="form-group">
          <label for="video4">Video 4 Link :</label>
          <input type="text" class="form-control" name="video4" value="{{ $share->video4 }}" />
          </div>

           <div class="form-group">
          <label for="video5">Video 5 Link :</label>
          <input type="text" class="form-control" name="video5" value="{{ $share->video5 }}" />
          </div>

           <div class="form-group">
          <label for="video6">Video 6 Link :</label>
          <input type="text" class="form-control" name="video6" value="{{ $share->video6 }}" />
          </div>


           <div class="form-group">
          <label for="teamdescription">Team description</label>
          <input type="text" class="form-control" name="teamdescrption" value="{{ $share->teamdescription }}" />
          </div>

          <div class="form-group">
          <label for="team1">Team member 1</label>
          <input type="text" class="form-control" name="team1" value="{{ $share->team1 }}" />
          </div>

          <div class="form-group">
          <label for="team1t">Team member title</label>
          <input type="text" class="form-control" name="team1t" value="{{ $share->team1t }}" />
          </div>

           <div class="form-group">
          <label for="team2">Team member 2</label>
          <input type="text" class="form-control" name="team2" value="{{ $share->team2 }}" />
          </div>

          <div class="form-group">
          <label for="team2t">Team member 2 title</label>
          <input type="text" class="form-control" name="team2t" value="{{ $share->team2t }}" />
          </div>

           <div class="form-group">
          <label for="team3">Team member 3</label>
          <input type="text" class="form-control" name="team3" value="{{ $share->team3 }}" />
          </div>

          <div class="form-group">
          <label for="team3t">Team member 3 title</label>
          <input type="text" class="form-control" name="team3t" value="{{ $share->team3 }}" />
          </div>

          <div class="form-group">
          <label for="team4">Team member 4</label>
          <input type="text" class="form-control" name="team4" value="{{ $share->team4 }}" />
          </div>


          <div class="form-group">
          <label for="team4t">Team member 4 title</label>
          <input type="text" class="form-control" name="team4t" value="{{ $share->team4t }}" />
          </div>

           <div class="form-group">
          <label for="testimonyname">Testimony Owner</label>
          <input type="text" class="form-control" name="testimonyname" value="{{ $share->testimonyname }}" />
          </div>
            
             <div class="form-group">
          <label for="testimonyoc">Testimony Owner Occupation</label>
          <input type="text" class="form-control" name="testimonyoc" value="{{ $share->testimonyoc }}" />
          </div>

            <div class="form-group">
          <label for="testimony">Testimony</label>
          <input type="text" class="form-control" name="testimony" value="{{ $share->testimony }}" />
          </div>

           <div class="form-group">
          <label for="fb">Facebook link</label>
          <input type="text" class="form-control" name="fb" value="{{ $share->fb }}" />
          </div>

           <div class="form-group">
          <label for="twitter">Twitter link</label>
          <input type="text" class="form-control" name="twitter" value="{{ $share->twitter }}" />
          </div>

           <div class="form-group">
          <label for="instagram">Instagram link</label>
          <input type="text" class="form-control" name="instagram" value="{{ $share->instagram }}" />
          </div>



















        <button type="submit" class="btn btn-primary">Update</button>
      </form>

  </div>
</div>
 <td>
               <a href="{{ url('/')}}" class="btn btn-primary">GO BACK TO WEBSITE</a > 
            </td>
@endsection

resources/views/shares/index.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Emmanuel Bako Website Content</td>
         
         
        </tr>
    </thead>
    <tbody>
        @foreach($shares as $share)
        <tr>
            <td>{{$share->id}}</td>
            <td>{{$share->share_name}}</td>
           
            <td><a href="{{ route('shares.edit',$share->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
               <a href="{{ url('/')}}" class="btn btn-primary">GO BACK TO WEBSITE</a > 
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection